---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    # TekuValidatorService
    - name: Read TekuValidatorService file
      slurp:
        src: "/etc/stereum/services/365500b1-285c-f88d-7d6c-3cde7b3ed973.yaml"
      register: Teku_service_configuration_raw

    - name: Parse Service configurations
      set_fact:
        Teku_service_configuration: "{{ Teku_service_configuration_raw['content'] | b64decode | from_yaml }}"

    - debug:
        msg: "{{ Teku_service_configuration }}"
    - debug:
        msg: "{{ Teku_service_configuration_raw['content'] | b64decode }}"

    - assert:
        that:
          - Teku_service_configuration.command | select('match', '--validators-proposer-blinded-blocks-enabled') | length == 0
# EOF
